### ISSUE TITLE
编译报错系列

### ISSUE THREAD

**Issue by sino1641** [Qrilee/MusicUU#2]
Android Studio默认配置编译报错。
~\MusicUU-master\app\src\main\java\com\qtfreet\musicuu\wiget\SystemBarTintManager.java 
Error:(35, 47) 警告: [unchecked] 对作为原始类型Class的成员的getDeclaredMethod(String,Class<?>...)的调用未经过检查
Error:Error: Expected resource of type styleable [ResourceType]

**Comment by Qrilee** [comment]
这个文件没有用到，工程中已经删除了
